### ISSUE TITLE
Adding a delimiter for elements

### ISSUE THREAD

**Issue by jamez2128** [LinArcX/wmenu#4]
Hi can I add a feature where you can use any character for a delimiter for parsing options aside from using ";"? Even though it is okay for options without any symbols but it is not ideal for some strings that may contains it. It even parses using \n just like how dmenu works originally. You specify the delimiter by using the -element-delimiter.

Examples:

When using \n:
![image](https://github.com/LinArcX/wmenu/assets/21281807/f1700c05-a560-499a-b9fe-2f6af9348593)
![image](https://github.com/LinArcX/wmenu/assets/21281807/1b741bd6-0cdc-4297-99d1-240193330654)
![image](https://github.com/LinArcX/wmenu/assets/21281807/00dae59d-8848-4724-8668-b7ece20efd55)

When using ;:
![image](https://github.com/LinArcX/wmenu/assets/21281807/c2e03a1a-6015-446a-bbf9-613f218702e8)
![image](https://github.com/LinArcX/wmenu/assets/21281807/0d90b18d-74d3-4075-9497-03998b8db5be)
![image](https://github.com/LinArcX/wmenu/assets/21281807/1ab95087-7ea2-4341-85c2-7c35df4ce880)

When using ,:
![image](https://github.com/LinArcX/wmenu/assets/21281807/e45d6a3a-7012-4f34-bde1-1902c25c17e1)
![image](https://github.com/LinArcX/wmenu/assets/21281807/fbfb35d9-163b-4b69-ab2a-547350f48a73)
![image](https://github.com/LinArcX/wmenu/assets/21281807/54203f9d-61d4-4882-8a4e-5548eb04aa2e)

When using a space:
![image](https://github.com/LinArcX/wmenu/assets/21281807/502b4a5d-c1c6-49b7-8e00-f60782c220bb)
![image](https://github.com/LinArcX/wmenu/assets/21281807/53cf12f4-c03d-4119-a7a7-29842ccfd0c0)
![image](https://github.com/LinArcX/wmenu/assets/21281807/a69f1658-5f18-449f-8514-5bb5a26e3b12)

and if -element-delimiter is not specified, it uses a default delimiter. 

Note: \n does not work in cmd or in batch scripts and it only works in other shells like powershell or in WSL according to my tests so far.

**Comment by LinArcX** [comment]
Hello and thank you for this idea.

I noticed that most of the times on windows we use `;` a lot, for example environment variables.

Among these options as default delimiter:
`,`
` `
`:`
`-`
`_`
`|`
  
I think it's better to stick with `,` since it's a single key press(unlike `|` or `_` or `:` that needs user to press SHIFT on a normal keyboard)

Another thing is that I don't like to accept any char as delimiter. like `~` or `^`.

I prefer a list of clean characters that are familiar for everyone: `,`,`;`, ` `, `:`, `-`, `_`, `|`.
